db:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  checkout_timeout: 5
  database: <%= ENV['RDS_DBNAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>